/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClassComparisonChart: typeof import('./components/statistics/ClassComparisonChart.vue')['default']
    PassRatePieChart: typeof import('./components/statistics/PassRatePieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreDistributionChart: typeof import('./components/statistics/ScoreDistributionChart.vue')['default']
    ScoreTrendChart: typeof import('./components/statistics/ScoreTrendChart.vue')['default']
    StatCard: typeof import('./components/statistics/StatCard.vue')['default']
    StudentRadarChart: typeof import('./components/statistics/StudentRadarChart.vue')['default']
  }
}
